use std::path::Path;
use crate::models::{AnalysisResult, Severity};

pub fn write_markdown(result: &AnalysisResult) -> Result<(), String> {
    let output = render_markdown(result);
    print!("{}", output);
    Ok(())
}

pub fn render_markdown(result: &AnalysisResult) -> String {
    let mut out = String::new();

    out.push_str("# 🗻 Fuji Analysis Report\n\n");
    out.push_str(&format!("**Directory:** `{}`\n\n", result.root_dir));

    // Summary
    out.push_str("## Summary\n\n");
    out.push_str("| Metric | Value |\n");
    out.push_str("|--------|-------|\n");
    out.push_str(&format!("| Files Analyzed | {} |\n", result.summary.files_analyzed));
    out.push_str(&format!("| Files Flagged | {} |\n", result.summary.files_flagged));
    out.push_str(&format!("| Average Complexity | {:.1} |\n", result.summary.avg_complexity));
    out.push_str(&format!("| Total Issues | {} |\n", result.summary.total_issues));
    out.push_str(&format!("| AI-Suspected Files | {} |\n", result.summary.ai_suspected));
    out.push_str(&format!("| Security Issues | {} |\n\n", result.summary.security_issues));

    // Group issues by severity
    struct FileIssue {
        path: String,
        line: usize,
        issue_type: String,
        message: String,
    }

    let mut critical = Vec::new();
    let mut errors = Vec::new();
    let mut warnings = Vec::new();
    let mut infos = Vec::new();

    let root = Path::new(&result.root_dir);

    for f in &result.files {
        if f.issues.is_empty() { continue; }
        let file_path = Path::new(&f.path);
        let rel_path = file_path
            .strip_prefix(root)
            .unwrap_or(file_path)
            .to_string_lossy()
            .to_string();

        for issue in &f.issues {
            let fi = FileIssue {
                path: rel_path.clone(),
                line: issue.line,
                issue_type: issue.issue_type.clone(),
                message: issue.message.clone(),
            };
            match issue.severity {
                Severity::Critical => critical.push(fi),
                Severity::Error => errors.push(fi),
                Severity::Warning => warnings.push(fi),
                Severity::Info | Severity::Note | Severity::None => infos.push(fi),
            }
        }
    }

    fn write_issue_table(out: &mut String, title: &str, issues: &[FileIssue]) {
        if issues.is_empty() { return; }
        out.push_str(&format!("## {}\n\n", title));
        out.push_str("| File | Line | Type | Message |\n");
        out.push_str("|------|------|------|--------|\n");
        for fi in issues {
            out.push_str(&format!("| `{}` | {} | {} | {} |\n",
                fi.path, fi.line, fi.issue_type, fi.message));
        }
        out.push_str("\n");
    }

    write_issue_table(&mut out, "🔴 Critical Issues", &critical);
    write_issue_table(&mut out, "🟠 Errors", &errors);
    write_issue_table(&mut out, "🟡 Warnings", &warnings);
    write_issue_table(&mut out, "🔵 Info", &infos);

    // AI-suspected files
    let ai_files: Vec<_> = result.files.iter().filter(|f| f.ai_probability > 50.0).collect();
    if !ai_files.is_empty() {
        out.push_str("## 🤖 AI-Suspected Files\n\n");
        out.push_str("| File | AI Probability | Complexity |\n");
        out.push_str("|------|---------------|------------|\n");
        for f in &ai_files {
            let file_path = Path::new(&f.path);
            let rel_path = file_path
                .strip_prefix(root)
                .unwrap_or(file_path)
                .to_string_lossy();
            let bar = make_bar(f.ai_probability / 100.0, 10);
            out.push_str(&format!("| `{}` | {} {:.0}% | {} |\n",
                rel_path, bar, f.ai_probability, f.complexity));
        }
        out.push_str("\n");
    }

    out.push_str("---\n\n");
    out.push_str("*Generated by [fuji](https://github.com/lichi/fuji) 🗻*\n");

    out
}

fn make_bar(ratio: f64, width: usize) -> String {
    let filled = (ratio * width as f64) as usize;
    let filled = filled.min(width);
    format!("{}{}", "█".repeat(filled), "░".repeat(width - filled))
}
